replicaCount: 1

image:
  repository: employee-manager
  tag: "1.0.0"
  pullPolicy: Always # Local Minikube image

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: employee.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

spring:
  profiles:
    active: default

health:
  path: /actuator/health
  initalDelay: 20
  period: 10

readinessProbe:
  initialDelaySeconds: 45


